/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlCategorie;
import Controlers.CtrlVehicule;
import Controlers.CtrlMoniteur;
import Controlers.CtrlUser;
import Entities.Moniteur;
import Entities.User;

import Controlers.CtrlCategorie;
import Controlers.CtrlVehicule;
import Tools.ConnexionBDD;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author Rosca
 */
public class FrmAjoutMoniteur extends javax.swing.JFrame {

    ConnexionBDD maCnx;
    int sexe;
    CtrlMoniteur ctrlMoniteur;
    CtrlVehicule ctrlVehicule;
    /**
     * 
     * Creates new form FrmModifInfoPerso
     */
    public FrmAjoutMoniteur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomAjoutMoniteur = new javax.swing.JTextField();
        txtPrenomAjoutMoniteur = new javax.swing.JTextField();
        txtAdresseAjoutMoniteur = new javax.swing.JTextField();
        txtCodePostalAjoutMoniteur = new javax.swing.JTextField();
        txtVilleAjoutMoniteur = new javax.swing.JTextField();
        txtTelephoneAjoutMoniteur = new javax.swing.JTextField();
        btnAjouterAjoutMoniteur = new javax.swing.JButton();
        lblNomAjoutMoniteur = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPrenomAjoutMoniteur = new javax.swing.JLabel();
        lblSexeAjoutMoniteur = new javax.swing.JLabel();
        lblDateDeNaissanceModifInfoPerso = new javax.swing.JLabel();
        lblAdresseAjoutMoniteur = new javax.swing.JLabel();
        lblCodePostalAjoutMoniteur = new javax.swing.JLabel();
        lblVilleAjoutMoniteur = new javax.swing.JLabel();
        lblTelephoneAjoutMoniteur = new javax.swing.JLabel();
        cboSexeAjoutMoniteur = new javax.swing.JComboBox<>();
        jdcDateNaissAjoutMoniteur = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtTelephoneAjoutMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneAjoutMoniteurActionPerformed(evt);
            }
        });

        btnAjouterAjoutMoniteur.setText("Ajouter");
        btnAjouterAjoutMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterAjoutMoniteurActionPerformed(evt);
            }
        });

        lblNomAjoutMoniteur.setText("Nom :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Ajout Moniteur");

        lblPrenomAjoutMoniteur.setText("Prénom :");

        lblSexeAjoutMoniteur.setText("Sexe :");

        lblDateDeNaissanceModifInfoPerso.setText("Date de naissance :");

        lblAdresseAjoutMoniteur.setText("Adresse :");

        lblCodePostalAjoutMoniteur.setText("Code Postal :");

        lblVilleAjoutMoniteur.setText("Ville :");

        lblTelephoneAjoutMoniteur.setText("Téléphone :");

        cboSexeAjoutMoniteur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(319, 319, 319))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomAjoutMoniteur)
                    .addComponent(lblPrenomAjoutMoniteur)
                    .addComponent(lblSexeAjoutMoniteur)
                    .addComponent(lblDateDeNaissanceModifInfoPerso)
                    .addComponent(lblAdresseAjoutMoniteur)
                    .addComponent(lblCodePostalAjoutMoniteur))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomAjoutMoniteur, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(txtPrenomAjoutMoniteur, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodePostalAjoutMoniteur)
                            .addComponent(txtAdresseAjoutMoniteur, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelephoneAjoutMoniteur)
                            .addComponent(lblVilleAjoutMoniteur))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVilleAjoutMoniteur, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(txtTelephoneAjoutMoniteur)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jdcDateNaissAjoutMoniteur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addComponent(cboSexeAjoutMoniteur, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnAjouterAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVilleAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomAjoutMoniteur)
                    .addComponent(lblVilleAjoutMoniteur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrenomAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelephoneAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrenomAjoutMoniteur)
                    .addComponent(lblTelephoneAjoutMoniteur))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSexeAjoutMoniteur)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cboSexeAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcDateNaissAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateDeNaissanceModifInfoPerso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdresseAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdresseAjoutMoniteur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodePostalAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodePostalAjoutMoniteur))
                .addGap(57, 57, 57)
                .addComponent(btnAjouterAjoutMoniteur)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelephoneAjoutMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneAjoutMoniteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneAjoutMoniteurActionPerformed

    
    
    
    
    private void btnAjouterAjoutMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterAjoutMoniteurActionPerformed
        // TODO add your handling code here:
        String Nom = txtNomAjoutMoniteur.getText();
        String Prenom = txtPrenomAjoutMoniteur.getText();
        
        String libelleSexe = String.valueOf(cboSexeAjoutMoniteur.getSelectedItem());
        if(libelleSexe.equals("Femme")){
             sexe =1;
        }   
        else{
             sexe =2; 
        } 
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        String datenaissance =sdf.format(jdcDateNaissAjoutMoniteur.getDate());
        String adresse = txtAdresseAjoutMoniteur.getText();
        String codepostal = txtCodePostalAjoutMoniteur.getText();
        String ville = txtVilleAjoutMoniteur.getText();
        String telephone =txtTelephoneAjoutMoniteur.getText();
        ctrlMoniteur = new CtrlMoniteur();
        ctrlMoniteur.AjoutMoniteur(Nom, Prenom, sexe, datenaissance, adresse, codepostal, ville, telephone);
        dispose();
    }//GEN-LAST:event_btnAjouterAjoutMoniteurActionPerformed
    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAjoutMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAjoutMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAjoutMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAjoutMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAjoutMoniteur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterAjoutMoniteur;
    private javax.swing.JComboBox<String> cboSexeAjoutMoniteur;
    private javax.swing.JLabel jLabel2;
    private com.toedter.calendar.JDateChooser jdcDateNaissAjoutMoniteur;
    private javax.swing.JLabel lblAdresseAjoutMoniteur;
    private javax.swing.JLabel lblCodePostalAjoutMoniteur;
    private javax.swing.JLabel lblDateDeNaissanceModifInfoPerso;
    private javax.swing.JLabel lblNomAjoutMoniteur;
    private javax.swing.JLabel lblPrenomAjoutMoniteur;
    private javax.swing.JLabel lblSexeAjoutMoniteur;
    private javax.swing.JLabel lblTelephoneAjoutMoniteur;
    private javax.swing.JLabel lblVilleAjoutMoniteur;
    private javax.swing.JTextField txtAdresseAjoutMoniteur;
    private javax.swing.JTextField txtCodePostalAjoutMoniteur;
    private javax.swing.JTextField txtNomAjoutMoniteur;
    private javax.swing.JTextField txtPrenomAjoutMoniteur;
    private javax.swing.JTextField txtTelephoneAjoutMoniteur;
    private javax.swing.JTextField txtVilleAjoutMoniteur;
    // End of variables declaration//GEN-END:variables
}
