/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

/**
 *
 * @author khali
 */
public class FrmAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdmin
     */
    public FrmAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAjouterVehicule = new javax.swing.JButton();
        btnModifVehicule = new javax.swing.JButton();
        btnModifCategorie = new javax.swing.JButton();
        btnAjouterCategorie = new javax.swing.JButton();
        btnAjouterMoniteur = new javax.swing.JButton();
        btnVisualiserLecon = new javax.swing.JButton();
        btnVisualiserEleve = new javax.swing.JButton();
        btnVisualiserMoniteur = new javax.swing.JButton();
        lblAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAjouterVehicule.setText("Ajouter Vehicule");
        btnAjouterVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterVehiculeActionPerformed(evt);
            }
        });

        btnModifVehicule.setText("Modifier Vehicule");
        btnModifVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifVehiculeActionPerformed(evt);
            }
        });

        btnModifCategorie.setText("Modifier Categorie");
        btnModifCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifCategorieActionPerformed(evt);
            }
        });

        btnAjouterCategorie.setText("Ajouter Categorie");
        btnAjouterCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterCategorieActionPerformed(evt);
            }
        });

        btnAjouterMoniteur.setText("Ajouter Moniteur");
        btnAjouterMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterMoniteurActionPerformed(evt);
            }
        });

        btnVisualiserLecon.setText("Visualiser leçon ");
        btnVisualiserLecon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualiserLeconActionPerformed(evt);
            }
        });

        btnVisualiserEleve.setText("Visualiser planning de l'eleve");
        btnVisualiserEleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualiserEleveActionPerformed(evt);
            }
        });

        btnVisualiserMoniteur.setText("Visualiser planning du moniteur");
        btnVisualiserMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualiserMoniteurActionPerformed(evt);
            }
        });

        lblAdmin.setForeground(new java.awt.Color(255, 0, 51));
        lblAdmin.setText("Responsable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjouterCategorie)
                    .addComponent(btnModifCategorie)
                    .addComponent(btnModifVehicule)
                    .addComponent(btnAjouterVehicule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualiserMoniteur)
                    .addComponent(btnVisualiserEleve)
                    .addComponent(btnVisualiserLecon)
                    .addComponent(btnAjouterMoniteur))
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAdmin)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAjouterMoniteur)
                        .addGap(18, 18, 18)
                        .addComponent(btnVisualiserLecon)
                        .addGap(18, 18, 18)
                        .addComponent(btnVisualiserMoniteur)
                        .addGap(18, 18, 18)
                        .addComponent(btnVisualiserEleve))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAjouterVehicule)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifVehicule)
                        .addGap(18, 18, 18)
                        .addComponent(btnAjouterCategorie)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifCategorie)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(lblAdmin)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterVehiculeActionPerformed
       FrmAjoutVehicule frm = new FrmAjoutVehicule();
       frm.setVisible(true);
    }//GEN-LAST:event_btnAjouterVehiculeActionPerformed

    private void btnModifVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifVehiculeActionPerformed
       FrmModiferVehicule frm = new FrmModiferVehicule();
       frm.setVisible(true);
    }//GEN-LAST:event_btnModifVehiculeActionPerformed

    private void btnAjouterCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterCategorieActionPerformed
       FrmAjoutCategorie frm = new FrmAjoutCategorie();
       frm.setVisible(true);
    }//GEN-LAST:event_btnAjouterCategorieActionPerformed

    private void btnModifCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifCategorieActionPerformed
       FrmModifierCategorie frm = new FrmModifierCategorie();
       frm.setVisible(true);
    }//GEN-LAST:event_btnModifCategorieActionPerformed

    private void btnAjouterMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterMoniteurActionPerformed
       FrmAjoutMoniteur frm = new FrmAjoutMoniteur();
       frm.setVisible(true);
    }//GEN-LAST:event_btnAjouterMoniteurActionPerformed

    private void btnVisualiserLeconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualiserLeconActionPerformed
       FrmMoniteurVisualiserToutesLesLecons frm = new FrmMoniteurVisualiserToutesLesLecons();
       frm.setVisible(true);
    }//GEN-LAST:event_btnVisualiserLeconActionPerformed

    private void btnVisualiserMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualiserMoniteurActionPerformed
       FrmAdministrateurVisualiserPlanningMoniteur frm = new FrmAdministrateurVisualiserPlanningMoniteur();
       frm.setVisible(true);
    }//GEN-LAST:event_btnVisualiserMoniteurActionPerformed

    private void btnVisualiserEleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualiserEleveActionPerformed
    FrmAdministrateurVisualiserPlanningEleve frm = new FrmAdministrateurVisualiserPlanningEleve();
    frm.setVisible(true);
    }//GEN-LAST:event_btnVisualiserEleveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterCategorie;
    private javax.swing.JButton btnAjouterMoniteur;
    private javax.swing.JButton btnAjouterVehicule;
    private javax.swing.JButton btnModifCategorie;
    private javax.swing.JButton btnModifVehicule;
    private javax.swing.JButton btnVisualiserEleve;
    private javax.swing.JButton btnVisualiserLecon;
    private javax.swing.JButton btnVisualiserMoniteur;
    private javax.swing.JLabel lblAdmin;
    // End of variables declaration//GEN-END:variables
}
