/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

/**
 *
 * @author Rosca
 */
public class FrmAjoutMoniteur extends javax.swing.JFrame {

    /**
     * Creates new form FrmModifInfoPerso
     */
    public FrmAjoutMoniteur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomAjoutMoniteur = new javax.swing.JTextField();
        txtPrenomAjoutMoniteur = new javax.swing.JTextField();
        txtAdresseAjoutMoniteur = new javax.swing.JTextField();
        txtCodePostalAjoutMoniteur = new javax.swing.JTextField();
        txtVilleAjoutMoniteur = new javax.swing.JTextField();
        txtTelephoneAjoutMoniteur = new javax.swing.JTextField();
        txtLoginAjoutMoniteur = new javax.swing.JTextField();
        txtMdpAjoutMoniteur = new javax.swing.JTextField();
        btnAjouterAjoutMoniteur = new javax.swing.JButton();
        btnAnnulerAjoutMoniteur = new javax.swing.JButton();
        lblNomAjoutMoniteur = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPrenomAjoutMoniteur = new javax.swing.JLabel();
        lblSexeAjoutMoniteur = new javax.swing.JLabel();
        lblDateDeNaissanceModifInfoPerso = new javax.swing.JLabel();
        lblAdresseAjoutMoniteur = new javax.swing.JLabel();
        lblCodePostalAjoutMoniteur = new javax.swing.JLabel();
        lblVilleAjoutMoniteur = new javax.swing.JLabel();
        lblTelephoneAjoutMoniteur = new javax.swing.JLabel();
        lblLoginAjoutMoniteur = new javax.swing.JLabel();
        lblMdpAjoutMoniteur = new javax.swing.JLabel();
        cboSexeAjoutMoniteur = new javax.swing.JComboBox<>();
        jdcDateNaissAjoutMoniteur = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtCodeMoniteurAjoutMoniteur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTelephoneAjoutMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneAjoutMoniteurActionPerformed(evt);
            }
        });

        txtLoginAjoutMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginAjoutMoniteurActionPerformed(evt);
            }
        });

        txtMdpAjoutMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMdpAjoutMoniteurActionPerformed(evt);
            }
        });

        btnAjouterAjoutMoniteur.setText("Ajouter");

        btnAnnulerAjoutMoniteur.setText("Annuler");

        lblNomAjoutMoniteur.setText("Nom :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Ajout Moniteur");

        lblPrenomAjoutMoniteur.setText("Prenom :");

        lblSexeAjoutMoniteur.setText("Sexe :");

        lblDateDeNaissanceModifInfoPerso.setText("Date de naissance :");

        lblAdresseAjoutMoniteur.setText("Adresse :");

        lblCodePostalAjoutMoniteur.setText("Code Postal :");

        lblVilleAjoutMoniteur.setText("Ville :");

        lblTelephoneAjoutMoniteur.setText("Téléphone :");

        lblLoginAjoutMoniteur.setText("Login :");

        lblMdpAjoutMoniteur.setText("Mdp :");

        cboSexeAjoutMoniteur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));

        jLabel1.setText("Code Moniteur :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(319, 319, 319))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomAjoutMoniteur)
                    .addComponent(lblPrenomAjoutMoniteur)
                    .addComponent(lblSexeAjoutMoniteur)
                    .addComponent(lblDateDeNaissanceModifInfoPerso)
                    .addComponent(lblAdresseAjoutMoniteur)
                    .addComponent(lblCodePostalAjoutMoniteur)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodeMoniteurAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdresseAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodePostalAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSexeAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrenomAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcDateNaissAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLoginAjoutMoniteur)
                                    .addComponent(lblTelephoneAjoutMoniteur)
                                    .addComponent(lblMdpAjoutMoniteur))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblVilleAjoutMoniteur)
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVilleAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelephoneAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoginAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMdpAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAjouterAjoutMoniteur)
                        .addGap(93, 93, 93)
                        .addComponent(btnAnnulerAjoutMoniteur)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodeMoniteurAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVilleAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomAjoutMoniteur)
                    .addComponent(lblVilleAjoutMoniteur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrenomAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelephoneAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrenomAjoutMoniteur)
                    .addComponent(lblTelephoneAjoutMoniteur))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSexeAjoutMoniteur)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblLoginAjoutMoniteur)
                                .addComponent(txtLoginAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cboSexeAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcDateNaissAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMdpAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDateDeNaissanceModifInfoPerso)
                        .addComponent(lblMdpAjoutMoniteur)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdresseAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdresseAjoutMoniteur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodePostalAjoutMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodePostalAjoutMoniteur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterAjoutMoniteur)
                    .addComponent(btnAnnulerAjoutMoniteur))
                .addGap(83, 83, 83))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelephoneAjoutMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneAjoutMoniteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneAjoutMoniteurActionPerformed

    private void txtLoginAjoutMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginAjoutMoniteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginAjoutMoniteurActionPerformed

    private void txtMdpAjoutMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMdpAjoutMoniteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMdpAjoutMoniteurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAjoutMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAjoutMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAjoutMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAjoutMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAjoutMoniteur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterAjoutMoniteur;
    private javax.swing.JButton btnAnnulerAjoutMoniteur;
    private javax.swing.JComboBox<String> cboSexeAjoutMoniteur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.toedter.calendar.JDateChooser jdcDateNaissAjoutMoniteur;
    private javax.swing.JLabel lblAdresseAjoutMoniteur;
    private javax.swing.JLabel lblCodePostalAjoutMoniteur;
    private javax.swing.JLabel lblDateDeNaissanceModifInfoPerso;
    private javax.swing.JLabel lblLoginAjoutMoniteur;
    private javax.swing.JLabel lblMdpAjoutMoniteur;
    private javax.swing.JLabel lblNomAjoutMoniteur;
    private javax.swing.JLabel lblPrenomAjoutMoniteur;
    private javax.swing.JLabel lblSexeAjoutMoniteur;
    private javax.swing.JLabel lblTelephoneAjoutMoniteur;
    private javax.swing.JLabel lblVilleAjoutMoniteur;
    private javax.swing.JTextField txtAdresseAjoutMoniteur;
    private javax.swing.JTextField txtCodeMoniteurAjoutMoniteur;
    private javax.swing.JTextField txtCodePostalAjoutMoniteur;
    private javax.swing.JTextField txtLoginAjoutMoniteur;
    private javax.swing.JTextField txtMdpAjoutMoniteur;
    private javax.swing.JTextField txtNomAjoutMoniteur;
    private javax.swing.JTextField txtPrenomAjoutMoniteur;
    private javax.swing.JTextField txtTelephoneAjoutMoniteur;
    private javax.swing.JTextField txtVilleAjoutMoniteur;
    // End of variables declaration//GEN-END:variables
}
