/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlEleve;
import Controlers.CtrlLecon;
import Entities.Lecon;
import Entities.User;
import Tools.ConnexionBDD;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author khali
 */
public class FrmEleveVisualiserPlanning extends javax.swing.JFrame {
    ConnexionBDD maCnx;
    DefaultMutableTreeNode racine;
    DefaultTreeModel model;
    DefaultMutableTreeNode Mois;
    DefaultMutableTreeNode Date;
    DefaultMutableTreeNode LibelleCategorie;
    DefaultMutableTreeNode Heure;
    DefaultMutableTreeNode Moniteur;
    DefaultMutableTreeNode Immatriculation;
    CtrlLecon ctrlLecon;
    CtrlEleve ctrlEleve;
    User user;
    /**
     * Creates new form FrmEleveMoniteurVisualiserPlanning
     */
    public FrmEleveVisualiserPlanning() {
        initComponents();
    }
    public FrmEleveVisualiserPlanning(User unUser){
        user = unUser;   
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlanning = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        trVisualiserEleve = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblPlanning.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPlanning.setText("Visualiser Planning");

        jScrollPane1.setViewportView(trVisualiserEleve);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblPlanning))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblPlanning)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        maCnx = new ConnexionBDD();
        ctrlLecon = new CtrlLecon();
        ctrlEleve = new CtrlEleve();
        racine = new DefaultMutableTreeNode("Toutes les leçons");
        racine.removeAllChildren();
        int idEleve = ctrlEleve.getIdEleveByNom(user.getNomUser());
        for(Lecon lecon : ctrlLecon.getAllLeconByIdEleveByTypePermis(idEleve)){
            Mois = new DefaultMutableTreeNode("Mois:"+lecon.getMois());
            Date = new DefaultMutableTreeNode("Date"+lecon.getDate());
            LibelleCategorie = new DefaultMutableTreeNode("Type Permis"+ lecon.getLibelleCategorie());
            Heure = new DefaultMutableTreeNode("Heure:"+lecon.getHeure());
            Moniteur = new DefaultMutableTreeNode("Nom Moniteur:"+lecon.getNomMoniteur());
            Immatriculation = new DefaultMutableTreeNode("Immatriculation:"+lecon.getImmatriculation());
            Date.add(Heure);
            Date.add(Moniteur);
            Date.add(Immatriculation);
            LibelleCategorie.add(Date);
            Mois.add(LibelleCategorie);
            racine.add(Mois);
        }
        model=  new DefaultTreeModel(racine);
        trVisualiserEleve.setModel(model);
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEleveVisualiserPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEleveVisualiserPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEleveVisualiserPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEleveVisualiserPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEleveVisualiserPlanning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPlanning;
    private javax.swing.JTree trVisualiserEleve;
    // End of variables declaration//GEN-END:variables
}
