/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlLecon;
import Controlers.CtrlMoniteur;
import Controlers.CtrlVehicule;
import Entities.User;
import Entities.Vehicule;
import Tools.ConnexionBDD;
import java.util.Date;

/**
 *
 * @author Rosca
 */
public class FrmInscrireAUneLecon extends javax.swing.JFrame {
    
    ConnexionBDD maCnx;
    CtrlMoniteur ctrlMoniteur;
    CtrlVehicule ctrlVehicule;
    CtrlLecon ctrlLecon;
    User user;
    /**
     * Creates new form FrmInscrireAUneLecon
     */
    public FrmInscrireAUneLecon() {
        initComponents();
    }
    public FrmInscrireAUneLecon(User unUser){
        user = unUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcInscrireLecon = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        cboPermisInscrireLecon = new javax.swing.JComboBox<>();
        lblHoraireInscrireLecon = new javax.swing.JLabel();
        txtHoraireInscrireLecon = new javax.swing.JTextField();
        cboMoniteurDispoInscrireLecon = new javax.swing.JComboBox<>();
        cboVoitureDispoInscrireLecon = new javax.swing.JComboBox<>();
        btnSinscrireInscrireLecon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("S'inscrire a une lecon");

        cboPermisInscrireLecon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Permis Voiture", "Permis Moto", "Permis Camion" }));
        cboPermisInscrireLecon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPermisInscrireLeconActionPerformed(evt);
            }
        });

        lblHoraireInscrireLecon.setText("Horaire :");

        cboMoniteurDispoInscrireLecon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMoniteurDispoInscrireLeconActionPerformed(evt);
            }
        });

        cboVoitureDispoInscrireLecon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboVoitureDispoInscrireLeconActionPerformed(evt);
            }
        });

        btnSinscrireInscrireLecon.setText("S'inscire");
        btnSinscrireInscrireLecon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinscrireInscrireLeconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcInscrireLecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHoraireInscrireLecon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHoraireInscrireLecon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboPermisInscrireLecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboVoitureDispoInscrireLecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboMoniteurDispoInscrireLecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(btnSinscrireInscrireLecon))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(171, 171, 171)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcInscrireLecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboPermisInscrireLecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMoniteurDispoInscrireLecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoraireInscrireLecon)
                            .addComponent(txtHoraireInscrireLecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboVoitureDispoInscrireLecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSinscrireInscrireLecon)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSinscrireInscrireLeconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinscrireInscrireLeconActionPerformed
        // TODO add your handling code here:
        ctrlMoniteur = new CtrlMoniteur();
        ctrlVehicule = new CtrlVehicule();
        ctrlLecon = new CtrlLecon();
        Date date = jcInscrireLecon.getDate();
        String heure = txtHoraireInscrireLecon.getText();
        int idMoniteur = ctrlMoniteur.getIdMoniteurByNom(cboMoniteurDispoInscrireLecon.getSelectedItem().toString());
        int idUser = user.getCodeEleve();
        String immatriculation = ctrlVehicule.getImmatriculationByModele(cboVoitureDispoInscrireLecon.getSelectedItem().toString());
        ctrlLecon.insertLecon(date, heure, idMoniteur, idUser, immatriculation, 1);
    }//GEN-LAST:event_btnSinscrireInscrireLeconActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ctrlMoniteur = new CtrlMoniteur();
        for(String moniteur : ctrlMoniteur.getAllNomMoniteur()){
            cboMoniteurDispoInscrireLecon.addItem(moniteur);
        }
        ctrlVehicule = new CtrlVehicule();
        if(cboPermisInscrireLecon.getSelectedItem().toString().equals("Permis Voiture")){
            for(Vehicule vehicule: ctrlVehicule.getVehiculesByCategorie(1)){
                cboVoitureDispoInscrireLecon.addItem(vehicule.getModele());
            }
        }
        else if(cboPermisInscrireLecon.getSelectedItem().toString().equals("Permis Moto")){
            for(Vehicule vehicule: ctrlVehicule.getVehiculesByCategorie(4)){
                cboVoitureDispoInscrireLecon.addItem(vehicule.getModele());
            }
        }
        else if(cboPermisInscrireLecon.getSelectedItem().toString().equals("Permis Camion")){
            for(Vehicule vehicule: ctrlVehicule.getVehiculesByCategorie(2)){
                cboVoitureDispoInscrireLecon.addItem(vehicule.getModele());
            }
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void cboPermisInscrireLeconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPermisInscrireLeconActionPerformed
        // TODO add your handling code here:
        ctrlVehicule = new CtrlVehicule();
        if(cboPermisInscrireLecon.getSelectedItem().toString().equals("Permis Voiture")){
            for(Vehicule vehicule: ctrlVehicule.getVehiculesByCategorie(1)){
                cboVoitureDispoInscrireLecon.addItem(vehicule.getModele());
            }
        }
        else if(cboPermisInscrireLecon.getSelectedItem().toString().equals("Permis Moto")){
            for(Vehicule vehicule: ctrlVehicule.getVehiculesByCategorie(4)){
                cboVoitureDispoInscrireLecon.addItem(vehicule.getModele());
            }
        }
        else if(cboPermisInscrireLecon.getSelectedItem().toString().equals("Permis Camion")){
            for(Vehicule vehicule: ctrlVehicule.getVehiculesByCategorie(2)){
                cboVoitureDispoInscrireLecon.addItem(vehicule.getModele());
            }
        }
    }//GEN-LAST:event_cboPermisInscrireLeconActionPerformed

    private void cboVoitureDispoInscrireLeconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboVoitureDispoInscrireLeconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboVoitureDispoInscrireLeconActionPerformed

    private void cboMoniteurDispoInscrireLeconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMoniteurDispoInscrireLeconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMoniteurDispoInscrireLeconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInscrireAUneLecon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInscrireAUneLecon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInscrireAUneLecon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInscrireAUneLecon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInscrireAUneLecon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSinscrireInscrireLecon;
    private javax.swing.JComboBox<String> cboMoniteurDispoInscrireLecon;
    private javax.swing.JComboBox<String> cboPermisInscrireLecon;
    private javax.swing.JComboBox<String> cboVoitureDispoInscrireLecon;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JCalendar jcInscrireLecon;
    private javax.swing.JLabel lblHoraireInscrireLecon;
    private javax.swing.JTextField txtHoraireInscrireLecon;
    // End of variables declaration//GEN-END:variables
}
