/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

/**
 *
 * @author khali
 */
public class FrmMoniteur extends javax.swing.JFrame {

    /**
     * Creates new form FrmMoniteur
     */
    public FrmMoniteur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModifInfoPerso = new javax.swing.JButton();
        btnVisualiserMonPlanning = new javax.swing.JButton();
        btnAjouterLicence = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnModifInfoPerso.setText("Modifier ses Informations Personnelles");
        btnModifInfoPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifInfoPersoActionPerformed(evt);
            }
        });

        btnVisualiserMonPlanning.setText("Visualiser mon planning");
        btnVisualiserMonPlanning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualiserMonPlanningActionPerformed(evt);
            }
        });

        btnAjouterLicence.setText("Ajouter une Licence");
        btnAjouterLicence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterLicenceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjouterLicence)
                    .addComponent(btnVisualiserMonPlanning)
                    .addComponent(btnModifInfoPerso))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnModifInfoPerso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisualiserMonPlanning)
                .addGap(18, 18, 18)
                .addComponent(btnAjouterLicence)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualiserMonPlanningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualiserMonPlanningActionPerformed
       FrmEleveVisualiserPlanning frm = new FrmEleveVisualiserPlanning();
       frm.setVisible(true);
    }//GEN-LAST:event_btnVisualiserMonPlanningActionPerformed

    private void btnModifInfoPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifInfoPersoActionPerformed
       FrmModifInfoPerso frm = new FrmModifInfoPerso ();
       frm.setVisible(true);
    }//GEN-LAST:event_btnModifInfoPersoActionPerformed

    private void btnAjouterLicenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterLicenceActionPerformed
    FrmModifInfoPerso frm = new FrmModifInfoPerso ();
     frm.setVisible(true);
    }//GEN-LAST:event_btnAjouterLicenceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMoniteur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterLicence;
    private javax.swing.JButton btnModifInfoPerso;
    private javax.swing.JButton btnVisualiserMonPlanning;
    // End of variables declaration//GEN-END:variables
}
