/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlCategorie;
import Controlers.CtrlVehicule;
import Entities.Vehicule;
import Tools.ConnexionBDD;
import Tools.ModelJTable;

/**
 *
 * @author Rosca
 */
public class FrmModiferVehicule extends javax.swing.JFrame {
    ConnexionBDD maCnx;
    CtrlVehicule ctrlVehicule;
    CtrlCategorie ctrlCategorie;
    ModelJTable mdl;
    /**
     * Creates new form FrmAjoutVehicule
     */
    public FrmModiferVehicule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitreModifVehicule = new javax.swing.JLabel();
        lblImmatriculationModifVehicule = new javax.swing.JLabel();
        lblMarqueModifVehicule = new javax.swing.JLabel();
        lblModeleModifVehicule = new javax.swing.JLabel();
        lblAnneeModifVehicule = new javax.swing.JLabel();
        lblLibCategorieModifVehicule = new javax.swing.JLabel();
        txtImmatriculationModifVehicule = new javax.swing.JTextField();
        txtMarqueModifVehicule = new javax.swing.JTextField();
        txtModeleModifVehicule = new javax.swing.JTextField();
        cboLibCategorieModifVehicule = new javax.swing.JComboBox<>();
        btnModifierModifVehicule = new javax.swing.JButton();
        btnAnnulerModifVehicule = new javax.swing.JButton();
        sprAnneeModifVehicule = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblModifVehicule = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitreModifVehicule.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTitreModifVehicule.setText("Modifier Véhicule");

        lblImmatriculationModifVehicule.setText("Immatriculation :");

        lblMarqueModifVehicule.setText("Marque :");

        lblModeleModifVehicule.setText("Modèle :");

        lblAnneeModifVehicule.setText("Année :");

        lblLibCategorieModifVehicule.setText("Libelle Catégorie :");

        btnModifierModifVehicule.setText("Modifier");
        btnModifierModifVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierModifVehiculeActionPerformed(evt);
            }
        });

        btnAnnulerModifVehicule.setText("Annuler");

        tblModifVehicule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblModifVehicule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblModifVehiculeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblModifVehicule);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImmatriculationModifVehicule)
                            .addComponent(lblMarqueModifVehicule)
                            .addComponent(lblModeleModifVehicule)
                            .addComponent(lblAnneeModifVehicule))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtModeleModifVehicule, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(txtMarqueModifVehicule)
                            .addComponent(txtImmatriculationModifVehicule)
                            .addComponent(sprAnneeModifVehicule, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLibCategorieModifVehicule)
                            .addComponent(btnModifierModifVehicule))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnnulerModifVehicule)
                            .addComponent(cboLibCategorieModifVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblTitreModifVehicule)
                        .addGap(411, 411, 411))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitreModifVehicule)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImmatriculationModifVehicule)
                    .addComponent(txtImmatriculationModifVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarqueModifVehicule)
                            .addComponent(txtMarqueModifVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModeleModifVehicule)
                            .addComponent(txtModeleModifVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnneeModifVehicule)
                            .addComponent(sprAnneeModifVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLibCategorieModifVehicule)
                            .addComponent(cboLibCategorieModifVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifierModifVehicule)
                    .addComponent(btnAnnulerModifVehicule))
                .addContainerGap(353, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        maCnx = new ConnexionBDD();
        ctrlVehicule = new CtrlVehicule();
        ctrlCategorie = new CtrlCategorie();
        for(String categorie : ctrlCategorie.getAllLibelleCategorie()){
            cboLibCategorieModifVehicule.addItem(categorie);
        }
        mdl = new ModelJTable();
        mdl.loadDatasVehicule(ctrlVehicule.getAllVehicule());
         tblModifVehicule.setModel(mdl);
    }//GEN-LAST:event_formWindowOpened

    private void tblModifVehiculeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblModifVehiculeMouseClicked
        // TODO add your handling code here:
        String immatriculation = String.valueOf(tblModifVehicule.getValueAt(tblModifVehicule.getSelectedRow(), 0));
        ctrlVehicule =new CtrlVehicule();
        
        Vehicule vehicule = ctrlVehicule.getVehiculeByImmatriculation(immatriculation);
        txtImmatriculationModifVehicule.setText(vehicule.getImmatriculation());
        txtMarqueModifVehicule.setText(vehicule.getMarque());
        txtModeleModifVehicule.setText(vehicule.getModele());
        sprAnneeModifVehicule.setValue(vehicule.getAnnee());
        cboLibCategorieModifVehicule.setSelectedItem(ctrlCategorie.getLibelleCategorieById(vehicule.getIdCategorie()));
        
    }//GEN-LAST:event_tblModifVehiculeMouseClicked

    private void btnModifierModifVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierModifVehiculeActionPerformed
        // TODO add your handling code here:
        String ancImmatriculation= String.valueOf(tblModifVehicule.getValueAt(tblModifVehicule.getSelectedRow(), 0));
        String nouvImmatriculation = txtImmatriculationModifVehicule.getText();
        String marque = txtMarqueModifVehicule.getText();
        String modele = txtModeleModifVehicule.getText();
        int annee =Integer.parseInt(String.valueOf(sprAnneeModifVehicule.getValue()));
        int idCategorie = ctrlCategorie.getIdCategorieByLibelle(String.valueOf(cboLibCategorieModifVehicule.getSelectedItem()));
        ctrlVehicule.UpdateVehicule(ancImmatriculation, nouvImmatriculation, marque, modele, annee, idCategorie);
    }//GEN-LAST:event_btnModifierModifVehiculeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModiferVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModiferVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModiferVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModiferVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModiferVehicule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnulerModifVehicule;
    private javax.swing.JButton btnModifierModifVehicule;
    private javax.swing.JComboBox<String> cboLibCategorieModifVehicule;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnneeModifVehicule;
    private javax.swing.JLabel lblImmatriculationModifVehicule;
    private javax.swing.JLabel lblLibCategorieModifVehicule;
    private javax.swing.JLabel lblMarqueModifVehicule;
    private javax.swing.JLabel lblModeleModifVehicule;
    private javax.swing.JLabel lblTitreModifVehicule;
    private javax.swing.JSpinner sprAnneeModifVehicule;
    private javax.swing.JTable tblModifVehicule;
    private javax.swing.JTextField txtImmatriculationModifVehicule;
    private javax.swing.JTextField txtMarqueModifVehicule;
    private javax.swing.JTextField txtModeleModifVehicule;
    // End of variables declaration//GEN-END:variables
}
