/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlMoniteur;
import Controlers.CtrlLecon;
import Entities.Lecon;
import Entities.User;
import Tools.ConnexionBDD;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author khaln
 */
public class FrmMoniteurVisualiserPlanning extends javax.swing.JFrame {
    User user;
    ConnexionBDD maCnx;
    DefaultMutableTreeNode racine;
    DefaultTreeModel model;
    DefaultMutableTreeNode Mois;
    DefaultMutableTreeNode Date;
    DefaultMutableTreeNode LibelleCategorie;
    DefaultMutableTreeNode Heure;
    DefaultMutableTreeNode Eleve;
    DefaultMutableTreeNode Immatriculation;
    CtrlLecon ctrlLecon;
    CtrlMoniteur ctrlMoniteur;
    /*
     * Creates new form FrmMoniteurVisualiserPlanning
     */
    public FrmMoniteurVisualiserPlanning() {
        initComponents();
    }
    public FrmMoniteurVisualiserPlanning(User unUser) {
        user = unUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        trVisualiserMoniteur = new javax.swing.JTree();
        lblPlanning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setViewportView(trVisualiserMoniteur);

        lblPlanning.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPlanning.setText("Visualiser Planning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(lblPlanning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblPlanning)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        maCnx = new ConnexionBDD();
        ctrlLecon = new CtrlLecon();
        ctrlMoniteur = new CtrlMoniteur();
        racine = new DefaultMutableTreeNode("Toutes les leçons");
        racine.removeAllChildren();
        int idMoniteur = ctrlMoniteur.getIdMoniteurByNom(user.getNomUser());
        for(Lecon lecon : ctrlLecon.getAllLeconByIdMoniteurByTypePermis(idMoniteur)){
            Mois = new DefaultMutableTreeNode("Mois: "+lecon.getMois());
            Date = new DefaultMutableTreeNode("Date "+lecon.getDate());
            LibelleCategorie = new DefaultMutableTreeNode("Type Permis "+ lecon.getLibelleCategorie());
            Heure = new DefaultMutableTreeNode("Heure: "+lecon.getHeure());
            Eleve = new DefaultMutableTreeNode("Nom Eleve: "+lecon.getNomEleve());
            Immatriculation = new DefaultMutableTreeNode("Immatriculation: "+lecon.getImmatriculation());
            Date.add(Heure);
            Date.add(Eleve);
            Date.add(Immatriculation);
            LibelleCategorie.add(Date);
            Mois.add(LibelleCategorie);
            racine.add(Mois);
        }
        model=  new DefaultTreeModel(racine);
        trVisualiserMoniteur.setModel(model);
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurVisualiserPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurVisualiserPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurVisualiserPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMoniteurVisualiserPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMoniteurVisualiserPlanning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPlanning;
    private javax.swing.JTree trVisualiserMoniteur;
    // End of variables declaration//GEN-END:variables
}
